language: java
install: true

dist: trusty
jdk: openjdk8

before_script:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download

script:
  - ./gradlew build --stacktrace
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
