language: java
install: true

dist: trusty
jdk: openjdk8

script:
  - ./gradlew build --stacktrace
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r report.xml --commit-uuid 397f61e3dd1144ee83792f936c7de80c
